In [1]:
# Import tensorflow
import tensorflow as tf

In [2]:
print(tf.__version__)

2.3.1


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
# Check the dimension of vector
vector.ndim

1

In [7]:
# Create a matrix( has >1 dimension)
matrix = tf.constant([[10,7], 
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]], dtype = tf.float16)

In [10]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# Number of dimension
another_matrix.ndim

2

In [12]:
# Let's create a tensor :)
tensor = tf.constant( [[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tensor.ndim

3

In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [16]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [17]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [22]:
unchangeable_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [23]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [25]:
# Creating random tensors
# Random tensors are of arbitary size with random numbers...

In [26]:
# Createa two random ( but the same ) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal( shape=(3,2) )
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [27]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [28]:
# Shuffle the order of the elements in a tensor. 
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [29]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [30]:
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [31]:
# shuffles along the one dimension. So it shuffles only the order of lists.
tf.random.shuffle(not_shuffled, seed = 42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [32]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [33]:
tf.random.shuffle(not_shuffled, seed = 42)                       

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [34]:
# We get different order everytime with operation level random seed.
# for global level random seed we get the same everytime.

In [35]:
tf.ones(shape = (10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [36]:
tf.zeros(shape=(100,100,100))

<tf.Tensor: shape=(100, 100, 100), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0

In [37]:
# Numpy arrays to tensors.
# The main difference between tensors and numpy arrays is that tensors can be run on GPUs/TPUs.
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
# X = tf.constant(some_matrix) # Capital letters
# y = tf.constant(vector) # small case

In [38]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [39]:
A = tf.constant(numpy_A, shape = (2,3,4))
A, numpy_A

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]))

In [40]:
A = tf.constant(numpy_A, shape = (6,4))
A, numpy_A

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]))

In [41]:
### Getting information from tensors.
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [42]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [43]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [44]:
rank_4_tensor.ndim

4

In [45]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [46]:
rank_4_tensor[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [47]:
print("Datatype pf every element: ", rank_4_tensor.dtype)

Datatype pf every element:  <dtype: 'float32'>


In [48]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [49]:
rank_4_tensor[1,1,1,:]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [50]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [51]:
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [52]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [53]:
# ADD in extra dimension.
rank_3_tensor = rank_2_tensor[..., tf.newaxis]


In [54]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [55]:
# ALternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [56]:
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]])>

In [57]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [58]:
### Manipulating the tensors...
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [59]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [60]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [61]:
tensor / 10, tensor // 10

(<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 0]])>)

In [62]:
# We can use the tensorflow built in function too.
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]])>

In [63]:
## Matrix multiplication
# In Machine Learning, matrix multiplication is one of the most common operation.
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [64]:
tensor  * tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]])>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [65]:
tensor @ tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [66]:
# create a tensor with shape(3,2)
x = tf.ones(shape=[3,2])
y = tf.ones(shape=[5,6])

In [67]:
tf.matmul(x,y)

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [5,6] [Op:MatMul]

In [ ]:
s = x.shape
tf.reshape(y, shape= (5,6))

In [68]:
tf.transpose(y) # transposing tensors

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [69]:
# matrix multiplication is also referred to as dot produt
# tf.matmul, x @ Y, tf.tensordot
# perform the dot product on x,y
# x or y needs to be transposed. then we need to reshape if required.
x @ tf.reshape( tf.transpose(y), shape = (2,15) )

<tf.Tensor: shape=(3, 15), dtype=float32, numpy=
array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]],
      dtype=float32)>

In [70]:
### Changing the datatype of a tensor.

B = tf.constant([1.7,2.4])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 2.4], dtype=float32)>

In [71]:
C = tf.constant([1,2,3])
C

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [72]:
# Change from float32 to float16.
# from 32-bit precsion to 16-bit precision
B = tf.cast(B, dtype=tf.float16)
B
# float16 runs faster than float32.


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 2.4], dtype=float16)>

In [73]:
#Change from int32 to float32 
C, C.dtype

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>, tf.int32)

In [74]:
## Aggregating tensors: condensing them from multiple values to smaller amount of values.
# Get the absolute values.
D = tf.constant([7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([  7, -10])>

In [75]:
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([  7, -10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>)

In [76]:
# Let's go through the following forms of aggregation:
    # Get the maximum 
    # Get the minimum
    # Mean and sum
X = tf.random.Generator.from_seed(42)
X = X.normal(shape=(5,6,7))
X

<tf.Tensor: shape=(5, 6, 7), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ,
         -0.23193763, -1.8107855 ,  0.09988727],
        [-0.50998646, -0.7535805 , -0.57166284,  0.1480774 ,
         -0.23362993, -0.3522796 ,  0.40621263],
        [-1.0523509 ,  1.2054597 ,  1.6874489 , -0.4462975 ,
         -2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 , -0.48293006,
         -0.52447474, -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ,
          0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034, -0.30288252,
         -1.443651  ,  1.0034493 ,  0.20857747]],

       [[ 0.35700995,  1.0648885 ,  1.2432485 , -2.2173238 ,
          0.18706243,  0.6617961 ,  0.01380118],
        [-0.24827152,  1.2111493 , -0.7199124 , -0.04082382,
          2.6791053 ,  1.0914806 ,  0.33149615],
        [-0.67958915,  0.44723678, -0.17811584,  0.24882518,
      

In [77]:
tf.reduce_mean(X), tf.reduce_max(X), tf.reduce_min(X), tf.reduce_sum(X)

(<tf.Tensor: shape=(), dtype=float32, numpy=-0.048848234>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.6791053>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-2.5255601>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-10.258129>)

In [78]:
std = tf.math.reduce_std(X)
std, std*std

(<tf.Tensor: shape=(), dtype=float32, numpy=0.969889>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9406846>)

In [79]:

import tensorflow_probability as tfp
tfp.stats.variance(X)

ModuleNotFoundError: No module named 'tensorflow_probability'

In [80]:
import pip
pip.__version__

'21.0.1'

In [81]:
# Create a new tensor for finding positional max and min
tf.random.set_seed(42)
D = tf.random.uniform(shape=[50])
D

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [82]:
tf.argmax(D)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [83]:
# Index on our largest value
D[tf.argmax(D)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [84]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [85]:
tf.argmin(D)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [86]:
D[tf.argmin(D)], tf.reduce_min(D)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [87]:
## Squeezing a tensor...
# Create a tensor 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [88]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [89]:
G_squeezed = tf.squeeze(G )
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

In [90]:
# One hot encoding
# Create a list of indices
some_list = [0,1,2,3]

# One hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [91]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [92]:
## squaring, log, square root
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [93]:
H*H, tf.square(H)

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>)